# Generated by Django 3.0.7 on 2020-09-16 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'Carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='idcategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('iddelivery', models.AutoField(db_column='idDelivery', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('precio', models.IntegerField(blank=True, db_column='Precio', null=True)),
            ],
            options={
                'db_table': 'Delivery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idmarca', models.AutoField(db_column='idmarca', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('foto', models.ImageField(db_column='Foto', upload_to='img/productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
            ],
            options={
                'db_table': 'Marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idmodulo', models.AutoField(db_column='idmodulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'Modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idtalla', models.AutoField(db_column='idtalla', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('modulo_idmodulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Modulo')),
            ],
            options={
                'db_table': 'Talla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('short', models.CharField(blank=True, db_column='Short', max_length=90, null=True)),
                ('precio', models.IntegerField(blank=True, db_column='Precio', null=True)),
                ('precio_promocion', models.IntegerField(blank=True, db_column='Precio promocion', null=True)),
                ('destacado', models.BooleanField(db_column='Destacado', default=False)),
                ('foto', models.FileField(db_column='Foto 1', upload_to='img/productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('foto2', models.FileField(db_column='Foto 2', upload_to='img/productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('foto3', models.FileField(db_column='Foto 3', upload_to='img/productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('promocion', models.IntegerField(blank=True, db_column='Promocion', null=True)),
                ('genero', models.CharField(blank=True, db_column='Genero', max_length=45, null=True)),
                ('preventa', models.IntegerField(blank=True, db_column='Pre venta', null=True)),
                ('categoria_idcategoria', models.ForeignKey(db_column='categoria_idcategoria', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Categoria')),
                ('marca_idmarca', models.ForeignKey(db_column='marca_idmarca', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Marca')),
                ('modulo_idmodulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Modulo')),
                ('tallas', models.ManyToManyField(to='mi_befashion.Talla')),
            ],
            options={
                'db_table': 'Producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Dirección', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('pedido', models.TextField(blank=True, db_column='Pedido', null=True)),
                ('notas', models.TextField(blank=True, db_column='Notas', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=45, null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
                ('total_delivery', models.IntegerField(blank=True, db_column='Total Delivery', null=True)),
                ('rut', models.CharField(blank=True, db_column='RUT', max_length=45, null=True)),
                ('delivery_iddelivery', models.ForeignKey(db_column='Delivery_idDelivery', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Delivery')),
            ],
            options={
                'db_table': 'Pedido',
                'managed': True,
                'unique_together': {('idpedido', 'delivery_iddelivery')},
            },
        ),
        migrations.CreateModel(
            name='Carritohasproductos',
            fields=[
                ('idcarritohasproductos', models.AutoField(db_column='idCarritoHasProductos', primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField(blank=True, db_column='Subtotal', null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('talla', models.CharField(blank=True, db_column='Talla', max_length=45, null=True)),
                ('carrito_idcarrito', models.ForeignKey(db_column='Carrito_idCarrito', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Carrito')),
                ('producto_idproducto', models.ForeignKey(db_column='Producto_idProducto', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Producto')),
            ],
            options={
                'db_table': 'CarritoHasProductos',
                'managed': True,
                'unique_together': {('idcarritohasproductos', 'carrito_idcarrito', 'producto_idproducto')},
            },
        ),
    ]
