# Generated by Django 3.0.7 on 2020-09-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='modulo_idmodulo',
            field=models.ForeignKey(db_column='modulo_idmodulo', default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Modulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='modulo_idmodulo',
            field=models.ForeignKey(db_column='modulo_idmodulo', default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Modulo'),
            preserve_default=False,
        ),
    ]
