# Generated by Django 3.0.7 on 2020-09-18 19:49

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_idcategoria',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='modulo_idmodulo', chained_model_field='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca_idmarca',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='modulo_idmodulo', chained_model_field='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tallas',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='modulo_idmodulo', chained_model_field='modulo_idmodulo', horizontal=True, to='mi_befashion.Talla', verbose_name='tallas'),
        ),
    ]
