# Generated by Django 3.0.7 on 2020-09-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0005_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
