# Generated by Django 3.0.7 on 2020-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0006_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFlow',
            fields=[
                ('idconfigflow', models.AutoField(db_column='idDelivery', primary_key=True, serialize=False)),
                ('secretkey', models.CharField(db_column='Secretkey', max_length=255)),
                ('apiKey', models.CharField(db_column='ApiKey', max_length=255)),
            ],
            options={
                'db_table': 'ConfiguracionFlow',
                'managed': True,
            },
        ),
    ]
