# Generated by Django 3.0.7 on 2020-09-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0008_delete_configuracionflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionPago',
            fields=[
                ('idintegrapago', models.AutoField(db_column='idDelivery', primary_key=True, serialize=False)),
                ('metodo_pago', models.IntegerField(choices=[('1', 'Mercado Pago'), ('2', 'FlowCL')], default=1)),
                ('mp_public_key', models.CharField(db_column='mp_public_key', max_length=255, null=True)),
                ('mp_access_token', models.CharField(db_column='mp_access_token', max_length=255, null=True)),
                ('fw_secretkey', models.CharField(db_column='fw_secretkey', max_length=255, null=True)),
                ('fw_apiKey', models.CharField(db_column='fw_apiKey', max_length=255, null=True)),
            ],
            options={
                'db_table': 'IntegracionPago',
                'managed': True,
            },
        ),
    ]
