# Generated by Django 3.0.7 on 2020-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0009_integracionpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracionpago',
            name='metodo_pago',
            field=models.IntegerField(choices=[(1, 'Mercado Pago'), (2, 'FlowCL')], default=1),
        ),
    ]
