# Generated by Django 3.0.7 on 2020-09-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0010_auto_20200921_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionpago',
            name='fw_url',
            field=models.CharField(db_column='fw_url', max_length=100, null=True),
        ),
    ]
