# Generated by Django 3.0.7 on 2020-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0012_auto_20200922_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePrueba',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Dirección', max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='industria',
            field=models.CharField(blank=True, db_column='Industria', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='razonsocial',
            field=models.CharField(blank=True, db_column='Razon Social', max_length=150, null=True),
        ),
    ]
