# Generated by Django 3.0.7 on 2020-09-24 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0013_auto_20200922_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto2',
            field=models.FileField(blank=True, db_column='Foto 2', null=True, upload_to='img/productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto3',
            field=models.FileField(blank=True, db_column='Foto 3', null=True, upload_to='img/productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
