# Generated by Django 3.0.7 on 2020-09-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0014_auto_20200924_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
    ]
