# Generated by Django 2.0 on 2020-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0015_remove_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_column='Activo', default=False),
        ),
    ]
