# Generated by Django 2.0 on 2020-10-16 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0016_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idalmacen', models.AutoField(db_column='idalmacen', primary_key=True, serialize=False)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('modulo_idmodulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Modulo')),
            ],
            options={
                'db_table': 'Almacen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.AutoField(db_column='idPromocion', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=90, null=True)),
                ('nombre_boton', models.CharField(blank=True, db_column='Boton_Name', max_length=20, null=True)),
                ('link_boton', models.CharField(blank=True, db_column='Link_Boton', max_length=255, null=True)),
                ('foto', models.FileField(db_column='Foto', upload_to='img/promociones', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('modulo_idmodulo', models.ForeignKey(db_column='modulo_idmodulo', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Modulo')),
            ],
            options={
                'db_table': 'Promocion',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, db_column='Ciudad', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(blank=True, db_column='Comuna', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='almacen',
            name='producto_idproducto',
            field=models.ForeignKey(db_column='producto_idproducto', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Producto'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='talla_idtalla',
            field=models.ForeignKey(db_column='talla_idtalla', on_delete=django.db.models.deletion.CASCADE, to='mi_befashion.Talla'),
        ),
    ]
