# Generated by Django 2.0 on 2020-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_befashion', '0017_auto_20201016_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_column='Activo', default=False),
        ),
    ]
